server:
  port: 8081

spring:
  application:
    name: xenia-test-server

external:
  api:
    baseUrl: https://xenia-qa.incubatelabs.com
    contentfulUrl: https://cdn.contentful.com/spaces/81nl0iyxht1e/environments/master/entries
    accessToken: 

